version: '3'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=brewcomp'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
    volumes:
      - './mysql_data:/var/lib/mysql'
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2

  redis:
    image: 'redis:latest'
    ports:
      - '6379'
    volumes:
      - './redis_data:/data'
    networks:
      mynetwork:
        ipv4_address: 172.20.0.3

  minio: &minio-common 
    image: quay.io/minio/minio:RELEASE.2023-11-15T20-43-25Z
    command: server --console-address ":9001" /data
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - './minio_data:/data'
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      mynetwork:
        ipv4_address: 172.20.0.4

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16
